use windows::Win32::UI::Input::KeyboardAndMouse::VIRTUAL_KEY;

// ---------------------------------------------------------------------------
// key code → label
// ---------------------------------------------------------------------------

pub fn vk_name(vk: u32, is_extended: bool) -> String {
    let vk = VIRTUAL_KEY(vk as u16);
    match vk {
        VIRTUAL_KEY(c @ 0x41..=0x5A) => format!("{}", c as u8 as char),
        VIRTUAL_KEY(c @ 0x30..=0x39) => format!("{}", (c as u8 - b'0')),
        VIRTUAL_KEY(c @ 0x70..=0x87) => format!("F{}", c - 0x6F),
        VIRTUAL_KEY(0x08) => "Backspace".into(),
        VIRTUAL_KEY(0x09) => "Tab".into(),
        VIRTUAL_KEY(0x0D) if is_extended => "NumEnter".into(),
        VIRTUAL_KEY(0x0D) => "Enter".into(),
        VIRTUAL_KEY(0x1B) => "Escape".into(),
        VIRTUAL_KEY(0x20) => "Space".into(),
        VIRTUAL_KEY(0x25) => "Left".into(),
        VIRTUAL_KEY(0x26) => "Up".into(),
        VIRTUAL_KEY(0x27) => "Right".into(),
        VIRTUAL_KEY(0x28) => "Down".into(),
        VIRTUAL_KEY(0x2E) => "Delete".into(),
        VIRTUAL_KEY(0x13) => "Pause".into(),
        VIRTUAL_KEY(0x21) => "PageUp".into(),
        VIRTUAL_KEY(0x22) => "PageDown".into(),
        VIRTUAL_KEY(0x23) => "End".into(),
        VIRTUAL_KEY(0x24) => "Home".into(),
        VIRTUAL_KEY(0x2C) => "PrtSc".into(),
        VIRTUAL_KEY(0x2D) => "Insert".into(),
        VIRTUAL_KEY(0x90) => "NumLock".into(),
        VIRTUAL_KEY(0x91) => "ScrollLock".into(),
        VIRTUAL_KEY(0x10) => "Shift".into(),
        VIRTUAL_KEY(0x11) => "Ctrl".into(),
        VIRTUAL_KEY(0x12) => "Alt".into(),
        VIRTUAL_KEY(0x14) => "CapsLock".into(),
        VIRTUAL_KEY(0x5B) | VIRTUAL_KEY(0x5C) => "Win".into(),
        VIRTUAL_KEY(0xA0) => "LShift".into(),
        VIRTUAL_KEY(0xA1) => "RShift".into(),
        VIRTUAL_KEY(0xA2) => "LCtrl".into(),
        VIRTUAL_KEY(0xA3) => "RCtrl".into(),
        VIRTUAL_KEY(0xA4) => "LAlt".into(),
        VIRTUAL_KEY(0xA5) => "RAlt".into(),
        VIRTUAL_KEY(0xBE) => ".".into(),
        VIRTUAL_KEY(0xBC) => ",".into(),
        VIRTUAL_KEY(0xBD) => "-".into(),
        VIRTUAL_KEY(0xBB) => "=".into(),
        VIRTUAL_KEY(0xDB) => "[".into(),
        VIRTUAL_KEY(0xDD) => "]".into(),
        VIRTUAL_KEY(0xDC) => "\\".into(),
        VIRTUAL_KEY(0xBA) => ";".into(),
        VIRTUAL_KEY(0xDE) => "'".into(),
        VIRTUAL_KEY(0xC0) => "`".into(),
        VIRTUAL_KEY(0xBF) => "/".into(),
        VIRTUAL_KEY(0xE2) => "<>".into(),
        VIRTUAL_KEY(c @ 0x60..=0x69) => format!("Num{}", c - 0x60),
        VIRTUAL_KEY(0x6A) => "Num*".into(),
        VIRTUAL_KEY(0x6B) => "Num+".into(),
        VIRTUAL_KEY(0x6D) => "Num-".into(),
        VIRTUAL_KEY(0x6E) => "Num.".into(),
        VIRTUAL_KEY(0x6F) => "Num/".into(),
        VIRTUAL_KEY(other) => format!("VK(0x{:02X})", other),
    }
}
