pub fn key_name(vk: u32, _extended: bool) -> String {
    let code = vk as u16;
    match code {
        // Escape & F-keys
        1 => "Escape".into(),
        59 => "F1".into(),
        60 => "F2".into(),
        61 => "F3".into(),
        62 => "F4".into(),
        63 => "F5".into(),
        64 => "F6".into(),
        65 => "F7".into(),
        66 => "F8".into(),
        67 => "F9".into(),
        68 => "F10".into(),
        87 => "F11".into(),
        88 => "F12".into(),
        // Number row
        41 => "`".into(),
        2 => "1".into(),
        3 => "2".into(),
        4 => "3".into(),
        5 => "4".into(),
        6 => "5".into(),
        7 => "6".into(),
        8 => "7".into(),
        9 => "8".into(),
        10 => "9".into(),
        11 => "0".into(),
        12 => "-".into(),
        13 => "=".into(),
        14 => "Backspace".into(),
        // QWERTY row
        15 => "Tab".into(),
        16 => "Q".into(),
        17 => "W".into(),
        18 => "E".into(),
        19 => "R".into(),
        20 => "T".into(),
        21 => "Y".into(),
        22 => "U".into(),
        23 => "I".into(),
        24 => "O".into(),
        25 => "P".into(),
        26 => "[".into(),
        27 => "]".into(),
        28 => "Enter".into(),
        // Home row
        58 => "CapsLock".into(),
        30 => "A".into(),
        31 => "S".into(),
        32 => "D".into(),
        33 => "F".into(),
        34 => "G".into(),
        35 => "H".into(),
        36 => "J".into(),
        37 => "K".into(),
        38 => "L".into(),
        39 => ";".into(),
        40 => "'".into(),
        43 => "\\".into(),
        // Bottom row
        42 => "LShift".into(),
        86 => "<>".into(),
        44 => "Z".into(),
        45 => "X".into(),
        46 => "C".into(),
        47 => "V".into(),
        48 => "B".into(),
        49 => "N".into(),
        50 => "M".into(),
        51 => ",".into(),
        52 => ".".into(),
        53 => "/".into(),
        54 => "RShift".into(),
        // Modifiers
        29 => "LCtrl".into(),
        97 => "RCtrl".into(),
        56 => "LAlt".into(),
        100 => "RAlt".into(),
        125 | 126 => "Win".into(),
        // Space & navigation
        57 => "Space".into(),
        102 => "Home".into(),
        103 => "Up".into(),
        104 => "PageUp".into(),
        105 => "Left".into(),
        106 => "Right".into(),
        107 => "End".into(),
        108 => "Down".into(),
        109 => "PageDown".into(),
        110 => "Insert".into(),
        111 => "Delete".into(),
        // Misc
        99 => "PrtSc".into(),
        69 => "NumLock".into(),
        70 => "ScrollLock".into(),
        119 => "Pause".into(),
        // Numpad
        71 => "Num7".into(),
        72 => "Num8".into(),
        73 => "Num9".into(),
        75 => "Num4".into(),
        76 => "Num5".into(),
        77 => "Num6".into(),
        79 => "Num1".into(),
        80 => "Num2".into(),
        81 => "Num3".into(),
        82 => "Num0".into(),
        83 => "Num.".into(),
        96 => "NumEnter".into(),
        55 => "Num*".into(),
        74 => "Num-".into(),
        78 => "Num+".into(),
        98 => "Num/".into(),
        other => format!("KEY({})", other),
    }
}
